### ISSUE TITLE
Error when running the sample

### ISSUE THREAD

**Issue by venkyvb** [niftylettuce/react-native-phone-verification#3]
BTW this seems to be a cool project !!

When I run the sample (https://github.com/joinspontaneous/react-native-phone-verification/blob/master/example/index.ios.js) I get the following error:

![image](https://cloud.githubusercontent.com/assets/740264/26613739/1914c482-4571-11e7-8dea-8fcb0ba583eb.png)

I also tried to create a new react native project from scratch, however the same issue exists.

**Comment by venkyvb** [comment]
Looks like this is related to a fix in the react-native-country-picker-modal (which is not yet merged - https://github.com/xcarpentier/react-native-country-picker-modal/issues/54). If you encounter the issue change the dependency in package.json to:

`"react-native-country-picker-modal":` `"github:xcarpentier/react-native-country-picker-modal"`

**Comment by niftylettuce** [comment]
I emailed the authors of that package to release the new version.  Will see what happens, otherwise will implement a different solution; more reliably maintained.

**Comment by niftylettuce** [comment]
Should be OK now - they released new version
